spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false
    username: root
    password: 367421
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
    hibernate:  
      ddl-auto: validate
  queries:
    users-query: select login, senha, status from voluntario where login=?
    roles-query: select u.login, r.role from voluntario u inner join voluntario_roles ur on(u.id=ur.voluntario_id) inner join role r on(ur.roles_id=r.id) where u.login=?
  mail:
    host: smtp.gmail.com
    port: 465
    username: intralacos@gmail.com
    password: 123465qw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
               
server:
  port: 7676